version: '2'

volumes:
  onisrc:

services:
  solr:
    image: solr:8-slim
    command:
      - solr-precreate
      - openoni
  test:
    build:
      context: ./docker
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/local/src/openoni:ro
      - onisrc:/opt/openoni
    depends_on:
      - solr
    environment:
      - ONLY_RUN_TESTS=1
      - APP_URL
